blank_issues_enabled: true
contact_links:
  - name: Issue
    about: Issue template
    url: https://github.com/otsuka-yuta/github-func-test/issues/new?template=hoge.md&projects=otsuka-yuta/1&labels=enhancement
