blank_issues_enabled: true
contact_links:
  - name: Issue
    about: Issue template
    url: https://github.com/otsuka-yuta/github-func-test/issues/new?template=issue.md&projects=otsuka-yuta/test&labels=enhancement
